MDGIVEMEMYREADINGLIST/MDGIVEMEMYREADINGLIST/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

MDGIVEMEMYREADINGLIST/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path(
        '', 
        views.index, 
        name='index'
        ),
    path(
        'readlist', 
        views.readlist, 
        name='readlist'
    ),
    path(
        'return_reading_list_json', 
        views.return_reading_list_json, 
        name='return_reading_list_json'
    ),
    path(
        'download_reading_list_as_csv',
        views.download_reading_list_as_csv,
        name='download_reading_list_as_csv'
    ),
    path(
        'blank', 
        views.blank, 
        name='blank'
    ),
]

MDGIVEMEMYREADINGLIST/main/models.py
from django.db import models

# Create your models here.

MDGIVEMEMYREADINGLIST/main/forms.py
from django import forms

class AuthForm(forms.Form):
    username = forms.CharField(label='Username', max_length=64)
    password = forms.CharField(label='Password', widget=forms.PasswordInput(), 
                                max_length=1024)

MDGIVEMEMYREADINGLIST/main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from .src import md_reading_list as mdrl
from .forms import AuthForm
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.http import JsonResponse
# Create your views here.

def index(request):
    form = AuthForm(request.POST)
    if form.is_valid():
        if token := login(form, request):
            request.session['token'] = token
            return HttpResponseRedirect(
                'readlist'
            )
    return render(
        request=request, 
        template_name='main/index.html', 
        context={ 'form':form }
    )

def login(form, request):
    payload = {
        'username': form.cleaned_data.get('username'),
        'password': form.cleaned_data.get('password')
    }
    token = mdrl.login(payload)
    if token == None:
        messages.error(request, 'Invalid username or password')
    return token

def readlist(request):
    print(request.session['token'])
    return render(request, 'main/readlist.html')   

def return_reading_list_json(request):
    session_token = request.session['token']
    
    follows = mdrl.get_follow_list(session_token)

    # for tests because mangadex's api is slow 
    # follows = follows[:5]

    read_chapters = mdrl.get_last_read(
        session_token, follows['id'].to_list()
    )
    
    last_read_chapter = mdrl.get_chapter_detail(read_chapters)

    reading_list = follows.join(
        last_read_chapter.set_index('id'), on='id'
    )

    # <a href="url">link text</a> 
    reading_list['mu_id'] = reading_list['mu_id'].map(
        lambda x: f'https://www.mangaupdates.com/series.html?id={x}' 
            if x else 'None'
    )

    reading_list.rename(
        columns={
            'title': 'Title',
            'last_read': 'Last Chapter Read',
            'chapter_title': 'Chapter Title',
            'mu_id': 'Mangaupdates Link'
        },
        inplace=True
    )

    request.session['reading_list_as_csv'] = reading_list.to_csv(
        encoding='utf-8'
    )

    reading_list_html = reading_list[
        ['Title', 'Last Chapter Read', 'Chapter Title', 'Mangaupdates Link']
    ].to_html(
        classes=['striped', 'responsive-table'],
        render_links=True,
        index=False,
    )

    return JsonResponse(
        {'content': reading_list_html},
        status=200
    )

def download_reading_list_as_csv(request):
    response = HttpResponse(
        content = request.session['reading_list_as_csv'],
        content_type = 'text/csv'
    )
    response['Content-Disposition'] = 'attachment; filename="Reading_List.csv"'
    
    return response

def blank(request):
    print('yeehaw')
    print('m8awejfklajsdf;aj;dsjf')
    return render(request, 'main/blank.html')

MDGIVEMEMYREADINGLIST/main/templates/main/blank.html
{% extends 'main/header.html' %}
{% load static %}


{% block content %}
    <body onload=get_blah()>
        <div id="#container">
            <div class="progress">
                <div class="indeterminate"></div>      
            </div>
            
            <p>THIS MAY TAKE A WHILE</p>
        </div>
    </body>

    
    {% block javascript %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>    
            function foo() {
                alert("done!")
            }

            function get_blah() {
                $.ajax({
                    type: "GET",
                    url: "{% url 'main:blah' %}",
                    success: function(data) {
                        console.log(data.content);
                        const container = document.getElementById("#container");
                        container.innerHTML = data.content;
                        $('#container').html(data);
                    }
                })
            }
        </script>
    {% endblock javascript %} 
    
    
{% endblock %}

MDGIVEMEMYREADINGLIST/main/templates/main/header.html
{% load static %}
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
    <!-- Compiled and minified CSS -->
    
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    
{% block javascript %}    
    <script src="{% static 'js/materialize.js' %}"></script>
{% endblock javascript %}

</head>

<main>
    <body class="grey darken-4">
        <div class="navbar-fixed">
            <nav>
                <div class="nav-wrapper grey darken-3">
                    <a class="brand-logo center">MANGADEX GIVE ME MY READING LIST REEEE</a>
                </div>
            </nav>
        </div>
        <div class="container">
            {% block content %}  
            {% endblock %}
        </div>
    </body>
</main>


<footer class="page-footer grey darken-2">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <p class="grey-text text-lighten-4">Your username and password is not stored, neither is your reading list. You can check source code to make sure ----></p>
        </div>
        <div class="col l4 offset-l2 s12">
          <ul>
            <li><a class="grey-text text-lighten-3" href="https://github.com/mdmn07C5/MDReadingList/tree/webv">Source code on github</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="footer-copyright grey darken-3">
      <div class="container">
      © 2021 What copyright lel
      </div>
    </div>
</footer>

MDGIVEMEMYREADINGLIST/main/templates/main/index.html
{% extends 'main/header.html' %}
  
{% block content %}
    <div class="row">
        <div class="col s6 offset-s3">
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title">Fan Shit Hitter</span>
                    <p>
                        Log in using your mangadex account.
                    </p>
                </div>
                <div class="card-action">
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn waves-effect waves-light grey darken-3" type="submit">gimme my fucking list</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% if messages %}
        {% for msg in messages %}
            <script>M.toast({html: "{{ msg }}"})</script>
        {% endfor %}
    {% endif %}
{% endblock %}

MDGIVEMEMYREADINGLIST/main/templates/main/readlist.html
{% extends 'main/header.html' %}

{% load static %}

{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
{% endblock javascript %}

{% block content %}

    <body onload=getReadingList()>
        <a href="{% url 'main:download_reading_list_as_csv' %}" onclick=disablePulse() id="download_button" class="waves-effect waves-light btn-large disabled"><i class="material-icons right">save_alt</i>download as csv</a>
        <span class="grey-text text-lighten-2">
            <div id="list_container">
                <h4 style="text-align: center">
                    Retrieving your reading list, this may take a while...
                </h4>
                <div class="progress">
                    <div class="indeterminate"></div>      
                </div>

                    <p class="flow-text ">
                        Some manga in your reading list may not have a latest chapter, most likely because the chapter upload has been nuked from MD's database.
                        Some manga won't have a mangaupdates link either (i.e. obscure twitter or pixiv manga).
                    </p>
            </div>
        </span>
    </body>
     
{% endblock %}